#
#     _______  __    __       _______. __    ______   .__   __.      _______.     ___       __           ___      .______      ____    ____
#    |   ____||  |  |  |     /       ||  |  /  __  \  |  \ |  |     /       |    /   \     |  |         /   \     |   _  \     \   \  /   /
#    |  |__   |  |  |  |    |   (----`|  | |  |  |  | |   \|  |    |   (----`   /  ^  \    |  |        /  ^  \    |  |_)  |     \   \/   /
#    |   __|  |  |  |  |     \   \    |  | |  |  |  | |  . `  |     \   \      /  /_\  \   |  |       /  /_\  \   |      /       \_    _/
#    |  |     |  `--'  | .----)   |   |  | |  `--'  | |  |\   | .----)   |    /  _____  \  |  `----. /  _____  \  |  |\  \----.    |  |
#    |__|      \______/  |_______/    |__|  \______/  |__| \__| |_______/    /__/     \__\ |_______|/__/     \__\ | _| `._____|    |__|
#
#  Плагин: FusionSalary v1.0
#  Автор: Skr4tch (DS: skr4tch.)
#
#  Студия: https://t.me/fusionstudio_ru
#  GitHub: https://github.com/skr4tchh/FusionSalary
#
# Зависимости: (Плагины без которых этот работать не будет)
#   Vault https://www.spigotmc.org/resources/vault.34315/
#
# Права:
#   fusionsalary.allow - дает доступ к получению зарплаты.
#

messages:
  prefix: "&6Зарплата §7» "
  perms: "&fУ вас недостаточно прав."
  cooldown: "&fВы сможете получить зарплату через &6%time%"
  not-salary: "&fДля вашей привилегии нету зарплаты."

salaries:
  king: # Название группы
    cooldown: 86400 # В секундах (86400 = 1 день)
    actions-on-give:
      - "[console] eco give %player% 1000"
#      - "[message] &6text"
#      - "[title] &etext;&atext"
#      - "[sound] ENTITY_EXPERIENCE_ORB_PICKUP"